# Generated by Django 4.2.15 on 2025-06-09 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id_pegawai', models.AutoField(primary_key=True, serialize=False)),
                ('nip', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nama_lengkap', models.CharField(blank=True, max_length=255, null=True)),
                ('jabatan', models.CharField(blank=True, max_length=100, null=True)),
                ('status_pegawai', models.CharField(choices=[('Aktif', 'Aktif'), ('Tidak Aktif', 'Tidak Aktif')], default='Aktif', max_length=15)),
            ],
            options={
                'db_table': 'pegawai',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
                ('nama_lengkap', models.CharField(blank=True, max_length=255, null=True)),
                ('status_akun', models.CharField(choices=[('Aktif', 'Aktif'), ('Tidak Aktif', 'Tidak Aktif')], default='Aktif', max_length=15)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Perizinan',
            fields=[
                ('id_izin', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_awal', models.DateField()),
                ('tanggal_akhir', models.DateField()),
                ('jenis_izin', models.CharField(choices=[('Sakit', 'Sakit'), ('Izin', 'Izin'), ('Cuti', 'Cuti Tahunan')], max_length=15)),
                ('keterangan', models.TextField()),
                ('file_lampiran', models.FileField(blank=True, null=True, upload_to='lampiran_izin/')),
                ('status_pengajuan', models.CharField(choices=[('Diajukan', 'Diajukan'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='Diajukan', max_length=15)),
                ('tanggal_pengajuan', models.DateTimeField(auto_now_add=True)),
                ('id_pegawai', models.ForeignKey(db_column='id_pegawai', on_delete=django.db.models.deletion.CASCADE, to='absensi.pegawai')),
            ],
            options={
                'db_table': 'perizinan',
            },
        ),
        migrations.AddField(
            model_name='pegawai',
            name='id_user',
            field=models.OneToOneField(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='absensi.user'),
        ),
        migrations.CreateModel(
            name='DataWajah',
            fields=[
                ('id_wajah', models.AutoField(primary_key=True, serialize=False)),
                ('data_embedding', models.TextField()),
                ('tanggal_enroll', models.DateTimeField(auto_now_add=True)),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='absensi.user')),
            ],
            options={
                'db_table': 'data_wajah',
            },
        ),
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id_absensi', models.AutoField(primary_key=True, serialize=False)),
                ('waktu_absensi', models.DateTimeField(auto_now_add=True)),
                ('tipe_absensi', models.CharField(choices=[('Masuk', 'Masuk'), ('Pulang', 'Pulang')], max_length=10)),
                ('status_verifikasi', models.CharField(choices=[('Berhasil', 'Berhasil'), ('Gagal', 'Gagal')], max_length=10)),
                ('foto_bukti', models.CharField(blank=True, max_length=255, null=True)),
                ('koordinat_lokasi', models.CharField(blank=True, max_length=255, null=True)),
                ('id_pegawai', models.ForeignKey(db_column='id_pegawai', on_delete=django.db.models.deletion.CASCADE, to='absensi.pegawai')),
            ],
            options={
                'db_table': 'absensi',
            },
        ),
    ]
